name: Daily Commit Bot

on:
  schedule:
    - cron: '13 3 * * *'  # Daily at 03:13 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Add empty commit with email 23f3001525@ds.study.iitm.ac.in
      run: |
        git commit --allow-empty -m "Daily commit by workflow"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
