name: Daily Commit Bot

on:
  schedule:
    - cron: '13 3 * * *'  # runs daily at 03:13 UTC
  workflow_dispatch:      # also allow manual run

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add empty commit with email 23f3001525@ds.study.iitm.ac.in
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit --allow-empty -m "Daily commit by workflow"
        git push
